const {
  requestFixture,
  requestLeagueStandings,
} = require('../models/api_fixtures');

let fixtureId = null;

testData = {
  id: 19104333,
  sport_id: 1,
  league_id: 271,
  season_id: 21644,
  stage_id: 77463994,
  group_id: null,
  aggregate_id: null,
  round_id: 336012,
  state_id: 2,
  venue_id: 1436,
  name: 'Nordsjælland vs AGF',
  starting_at: '2024-04-22 19:00:00',
  result_info: null,
  leg: '1/1',
  details: null,
  length: 90,
  placeholder: false,
  has_odds: true,
  starting_at_timestamp: 1713805200,
  round: {
    id: 336012,
    sport_id: 1,
    league_id: 271,
    season_id: 21644,
    stage_id: 77463994,
    name: '4',
    finished: false,
    is_current: true,
    starting_at: '2024-04-21',
    ending_at: '2024-04-22',
    games_in_current_week: true,
  },
  league: {
    id: 271,
    sport_id: 1,
    country_id: 320,
    name: 'Superliga',
    active: true,
    short_code: 'DNK SL',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/271.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-04-21 16:00:00',
    category: 2,
    has_jerseys: false,
    country: {
      id: 320,
      continent_id: 1,
      name: 'Denmark',
      official_name: 'Kingdom of Denmark',
      fifa_name: 'DEN',
      iso2: 'DK',
      iso3: 'DNK',
      latitude: '56.10176086425781',
      longitude: '9.555907249450684',
      borders: ['DEU'],
      image_path:
        'https://cdn.sportmonks.com/images/countries/png/short/dk.png',
    },
  },
  scores: [
    {
      id: 14286256,
      fixture_id: 19104333,
      type_id: 1525,
      participant_id: 2394,
      score: {
        goals: 2,
        participant: 'home',
      },
      description: 'CURRENT',
    },
    {
      id: 14286257,
      fixture_id: 19104333,
      type_id: 1525,
      participant_id: 2905,
      score: {
        goals: 1,
        participant: 'away',
      },
      description: 'CURRENT',
    },
    {
      id: 14286254,
      fixture_id: 19104333,
      type_id: 1,
      participant_id: 2394,
      score: {
        goals: 2,
        participant: 'home',
      },
      description: '1ST_HALF',
    },
    {
      id: 14286255,
      fixture_id: 19104333,
      type_id: 1,
      participant_id: 2905,
      score: {
        goals: 1,
        participant: 'away',
      },
      description: '1ST_HALF',
    },
  ],
  events: [
    {
      id: 111810835,
      fixture_id: 19104333,
      period_id: 5374028,
      participant_id: 2394,
      type_id: 14,
      section: 'event',
      player_id: 37549513,
      related_player_id: null,
      player_name: 'Ibrahim Osman',
      related_player_name: null,
      result: '2-1',
      info: 'Shot',
      addition: '3rd Goal',
      minute: 27,
      extra_minute: null,
      injured: null,
      on_bench: false,
      coach_id: null,
      sub_type_id: 1522,
      type: {
        id: 14,
        name: 'Goal',
        code: 'goal',
        developer_name: 'GOAL',
        model_type: 'event',
        stat_group: null,
      },
    },
    {
      id: 111810614,
      fixture_id: 19104333,
      period_id: 5374028,
      participant_id: 2394,
      type_id: 14,
      section: 'event',
      player_id: 37407422,
      related_player_id: 37555815,
      player_name: 'Daniel Svensson',
      related_player_name: 'Andreas Schjelderup',
      result: '1-0',
      info: 'Shot',
      addition: '1st Goal',
      minute: 13,
      extra_minute: null,
      injured: null,
      on_bench: false,
      coach_id: null,
      sub_type_id: 1522,
      type: {
        id: 14,
        name: 'Goal',
        code: 'goal',
        developer_name: 'GOAL',
        model_type: 'event',
        stat_group: null,
      },
    },
    {
      id: 111810756,
      fixture_id: 19104333,
      period_id: 5374028,
      participant_id: 2905,
      type_id: 14,
      section: 'event',
      player_id: 83665,
      related_player_id: 289659,
      player_name: 'Patrick Mortensen ',
      related_player_name: 'Gift Links',
      result: '1-1',
      info: 'Header',
      addition: '2nd Goal',
      minute: 23,
      extra_minute: null,
      injured: null,
      on_bench: false,
      coach_id: null,
      sub_type_id: 1522,
      type: {
        id: 14,
        name: 'Goal',
        code: 'goal',
        developer_name: 'GOAL',
        model_type: 'event',
        stat_group: null,
      },
    },
    {
      id: 111810864,
      fixture_id: 19104333,
      period_id: 5374028,
      participant_id: 2905,
      type_id: 19,
      section: 'event',
      player_id: 31616637,
      related_player_id: null,
      player_name: 'Magnus Knudsen',
      related_player_name: null,
      result: null,
      info: 'Foul',
      addition: null,
      minute: 29,
      extra_minute: null,
      injured: null,
      on_bench: false,
      coach_id: null,
      sub_type_id: 1496,
      type: {
        id: 19,
        name: 'Yellowcard',
        code: 'yellowcard',
        developer_name: 'YELLOWCARD',
        model_type: 'event',
        stat_group: null,
      },
    },
  ],
  participants: [
    {
      id: 2394,
      sport_id: 1,
      country_id: 320,
      venue_id: 1436,
      gender: 'male',
      name: 'Nordsjælland',
      short_code: 'FCN',
      image_path: 'https://cdn.sportmonks.com/images/soccer/teams/26/2394.png',
      founded: 2003,
      type: 'domestic',
      placeholder: false,
      last_played_at: '2024-04-15 17:00:00',
      meta: {
        location: 'home',
        winner: null,
        position: 4,
      },
    },
    {
      id: 2905,
      sport_id: 1,
      country_id: 320,
      venue_id: 1708,
      gender: 'male',
      name: 'AGF',
      short_code: 'AGF',
      image_path: 'https://cdn.sportmonks.com/images/soccer/teams/25/2905.png',
      founded: 1902,
      type: 'domestic',
      placeholder: false,
      last_played_at: '2024-04-14 14:00:00',
      meta: {
        location: 'away',
        winner: null,
        position: 5,
      },
    },
  ],
  periods: [
    {
      id: 5374028,
      fixture_id: 19104333,
      type_id: 1,
      started: 1713805250,
      ended: null,
      counts_from: 0,
      ticking: true,
      sort_order: 1,
      description: '1st-half',
      time_added: null,
      period_length: 45,
      minutes: 34,
      seconds: 31,
      has_timer: true,
    },
  ],
  state: {
    id: 2,
    state: 'INPLAY_1ST_HALF',
    name: '1st Half',
    short_name: '1st',
    developer_name: 'INPLAY_1ST_HALF',
    type: {
      id: 1,
      name: '1st Half',
      code: '1st-half',
      developer_name: '1ST_HALF',
      model_type: 'period',
      stat_group: null,
    },
  },
  statistics: [
    {
      id: 33626235,
      fixture_id: 19104333,
      type_id: 42,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 42,
        name: 'Shots Total',
        code: 'shots-total',
        developer_name: 'SHOTS_TOTAL',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628682,
      fixture_id: 19104333,
      type_id: 44,
      participant_id: 2905,
      data: {
        value: 13,
      },
      location: 'away',
      type: {
        id: 44,
        name: 'Dangerous Attacks',
        code: 'dangerous-attacks',
        developer_name: 'DANGEROUS_ATTACKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629564,
      fixture_id: 19104333,
      type_id: 78,
      participant_id: 2905,
      data: {
        value: 4,
      },
      location: 'away',
      type: {
        id: 78,
        name: 'Tackles',
        code: 'tackles',
        developer_name: 'TACKLES',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33629561,
      fixture_id: 19104333,
      type_id: 78,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 78,
        name: 'Tackles',
        code: 'tackles',
        developer_name: 'TACKLES',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33628722,
      fixture_id: 19104333,
      type_id: 84,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 84,
        name: 'Yellowcards',
        code: 'yellowcards',
        developer_name: 'YELLOWCARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628720,
      fixture_id: 19104333,
      type_id: 59,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 59,
        name: 'Substitutions',
        code: 'substitutions',
        developer_name: 'SUBSTITUTIONS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628912,
      fixture_id: 19104333,
      type_id: 58,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 58,
        name: 'Shots Blocked',
        code: 'shots-blocked',
        developer_name: 'SHOTS_BLOCKED',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630137,
      fixture_id: 19104333,
      type_id: 108,
      participant_id: 2394,
      data: {
        value: 4,
      },
      location: 'home',
      type: {
        id: 108,
        name: 'Dribble Attempts',
        code: 'dribble-attempts',
        developer_name: 'DRIBBLED_ATTEMPTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628684,
      fixture_id: 19104333,
      type_id: 41,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 41,
        name: 'Shots Off Target',
        code: 'shots-off-target',
        developer_name: 'SHOTS_OFF_TARGET',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628712,
      fixture_id: 19104333,
      type_id: 34,
      participant_id: 2394,
      data: {
        value: 5,
      },
      location: 'home',
      type: {
        id: 34,
        name: 'Corners',
        code: 'corners',
        developer_name: 'CORNERS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628677,
      fixture_id: 19104333,
      type_id: 43,
      participant_id: 2394,
      data: {
        value: 45,
      },
      location: 'home',
      type: {
        id: 43,
        name: 'Attacks',
        code: 'attacks',
        developer_name: 'ATTACKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628678,
      fixture_id: 19104333,
      type_id: 44,
      participant_id: 2394,
      data: {
        value: 16,
      },
      location: 'home',
      type: {
        id: 44,
        name: 'Dangerous Attacks',
        code: 'dangerous-attacks',
        developer_name: 'DANGEROUS_ATTACKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628683,
      fixture_id: 19104333,
      type_id: 86,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 86,
        name: 'Shots On Target',
        code: 'shots-on-target',
        developer_name: 'SHOTS_ON_TARGET',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628700,
      fixture_id: 19104333,
      type_id: 81,
      participant_id: 2905,
      data: {
        value: 136,
      },
      location: 'away',
      type: {
        id: 81,
        name: 'Successful Passes',
        code: 'successful-passes',
        developer_name: 'SUCCESSFUL_PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629293,
      fixture_id: 19104333,
      type_id: 106,
      participant_id: 2394,
      data: {
        value: 9,
      },
      location: 'home',
      type: {
        id: 106,
        name: 'Duels Won',
        code: 'duels-won',
        developer_name: 'DUELS_WON',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629238,
      fixture_id: 19104333,
      type_id: 77,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 77,
        name: 'Challenges',
        code: 'challenges',
        developer_name: 'CHALLENGES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628686,
      fixture_id: 19104333,
      type_id: 82,
      participant_id: 2905,
      data: {
        value: 83,
      },
      location: 'away',
      type: {
        id: 82,
        name: 'Successful Passes Percentage',
        code: 'successful-passes-percentage',
        developer_name: 'SUCCESSFUL_PASSES_PERCENTAGE',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628679,
      fixture_id: 19104333,
      type_id: 41,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 41,
        name: 'Shots Off Target',
        code: 'shots-off-target',
        developer_name: 'SHOTS_OFF_TARGET',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628711,
      fixture_id: 19104333,
      type_id: 83,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 83,
        name: 'Redcards',
        code: 'redcards',
        developer_name: 'REDCARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628911,
      fixture_id: 19104333,
      type_id: 58,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 58,
        name: 'Shots Blocked',
        code: 'shots-blocked',
        developer_name: 'SHOTS_BLOCKED',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628681,
      fixture_id: 19104333,
      type_id: 43,
      participant_id: 2905,
      data: {
        value: 36,
      },
      location: 'away',
      type: {
        id: 43,
        name: 'Attacks',
        code: 'attacks',
        developer_name: 'ATTACKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628716,
      fixture_id: 19104333,
      type_id: 84,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 84,
        name: 'Yellowcards',
        code: 'yellowcards',
        developer_name: 'YELLOWCARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33630106,
      fixture_id: 19104333,
      type_id: 53,
      participant_id: 2394,
      data: {
        value: 2,
      },
      location: 'home',
      type: {
        id: 53,
        name: 'Goal Kicks',
        code: 'goals-kicks',
        developer_name: 'GOAL_KICKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630107,
      fixture_id: 19104333,
      type_id: 53,
      participant_id: 2905,
      data: {
        value: 3,
      },
      location: 'away',
      type: {
        id: 53,
        name: 'Goal Kicks',
        code: 'goals-kicks',
        developer_name: 'GOAL_KICKS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628676,
      fixture_id: 19104333,
      type_id: 86,
      participant_id: 2394,
      data: {
        value: 2,
      },
      location: 'home',
      type: {
        id: 86,
        name: 'Shots On Target',
        code: 'shots-on-target',
        developer_name: 'SHOTS_ON_TARGET',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629237,
      fixture_id: 19104333,
      type_id: 65,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 65,
        name: 'Successful Headers',
        code: 'successful-headers',
        developer_name: 'SUCCESSFUL_HEADERS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33626234,
      fixture_id: 19104333,
      type_id: 42,
      participant_id: 2394,
      data: {
        value: 4,
      },
      location: 'home',
      type: {
        id: 42,
        name: 'Shots Total',
        code: 'shots-total',
        developer_name: 'SHOTS_TOTAL',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628713,
      fixture_id: 19104333,
      type_id: 47,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 47,
        name: 'Penalties',
        code: 'penalties',
        developer_name: 'PENALTIES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628721,
      fixture_id: 19104333,
      type_id: 83,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 83,
        name: 'Redcards',
        code: 'redcards',
        developer_name: 'REDCARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628718,
      fixture_id: 19104333,
      type_id: 52,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 52,
        name: 'Goals',
        code: 'goals',
        developer_name: 'GOALS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628715,
      fixture_id: 19104333,
      type_id: 59,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 59,
        name: 'Substitutions',
        code: 'substitutions',
        developer_name: 'SUBSTITUTIONS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628719,
      fixture_id: 19104333,
      type_id: 34,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 34,
        name: 'Corners',
        code: 'corners',
        developer_name: 'CORNERS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33628717,
      fixture_id: 19104333,
      type_id: 47,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 47,
        name: 'Penalties',
        code: 'penalties',
        developer_name: 'PENALTIES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629007,
      fixture_id: 19104333,
      type_id: 60,
      participant_id: 2394,
      data: {
        value: 6,
      },
      location: 'home',
      type: {
        id: 60,
        name: 'Throwins',
        code: 'throwins',
        developer_name: 'THROWINS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628680,
      fixture_id: 19104333,
      type_id: 82,
      participant_id: 2394,
      data: {
        value: 83,
      },
      location: 'home',
      type: {
        id: 82,
        name: 'Successful Passes Percentage',
        code: 'successful-passes-percentage',
        developer_name: 'SUCCESSFUL_PASSES_PERCENTAGE',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629321,
      fixture_id: 19104333,
      type_id: 100,
      participant_id: 2905,
      data: {
        value: 5,
      },
      location: 'away',
      type: {
        id: 100,
        name: 'Interceptions',
        code: 'interceptions',
        developer_name: 'INTERCEPTIONS',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33629008,
      fixture_id: 19104333,
      type_id: 60,
      participant_id: 2905,
      data: {
        value: 3,
      },
      location: 'away',
      type: {
        id: 60,
        name: 'Throwins',
        code: 'throwins',
        developer_name: 'THROWINS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629629,
      fixture_id: 19104333,
      type_id: 66,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 66,
        name: 'Successful Interceptions',
        code: 'successful-interceptions',
        developer_name: 'SUCCESSFUL_INTERCEPTIONS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629929,
      fixture_id: 19104333,
      type_id: 98,
      participant_id: 2905,
      data: {
        value: 3,
      },
      location: 'away',
      type: {
        id: 98,
        name: 'Total Crosses',
        code: 'total-crosses',
        developer_name: 'TOTAL_CROSSES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629322,
      fixture_id: 19104333,
      type_id: 106,
      participant_id: 2905,
      data: {
        value: 12,
      },
      location: 'away',
      type: {
        id: 106,
        name: 'Duels Won',
        code: 'duels-won',
        developer_name: 'DUELS_WON',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629563,
      fixture_id: 19104333,
      type_id: 56,
      participant_id: 2905,
      data: {
        value: 2,
      },
      location: 'away',
      type: {
        id: 56,
        name: 'Fouls',
        code: 'fouls',
        developer_name: 'FOULS',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33629636,
      fixture_id: 19104333,
      type_id: 66,
      participant_id: 2905,
      data: {
        value: 5,
      },
      location: 'away',
      type: {
        id: 66,
        name: 'Successful Interceptions',
        code: 'successful-interceptions',
        developer_name: 'SUCCESSFUL_INTERCEPTIONS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628698,
      fixture_id: 19104333,
      type_id: 80,
      participant_id: 2394,
      data: {
        value: 165,
      },
      location: 'home',
      type: {
        id: 80,
        name: 'Passes',
        code: 'passes',
        developer_name: 'PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628210,
      fixture_id: 19104333,
      type_id: 45,
      participant_id: 2905,
      data: {
        value: 49,
      },
      location: 'away',
      type: {
        id: 45,
        name: 'Ball Possession %',
        code: 'ball-possession',
        developer_name: 'BALL_POSSESSION',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629928,
      fixture_id: 19104333,
      type_id: 98,
      participant_id: 2394,
      data: {
        value: 8,
      },
      location: 'home',
      type: {
        id: 98,
        name: 'Total Crosses',
        code: 'total-crosses',
        developer_name: 'TOTAL_CROSSES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630395,
      fixture_id: 19104333,
      type_id: 117,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 117,
        name: 'Key Passes',
        code: 'key-passes',
        developer_name: 'KEY_PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33630134,
      fixture_id: 19104333,
      type_id: 99,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 99,
        name: 'Accurate Crosses',
        code: 'accurate-crosses',
        developer_name: 'ACCURATE_CROSSES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630136,
      fixture_id: 19104333,
      type_id: 109,
      participant_id: 2394,
      data: {
        value: 2,
      },
      location: 'home',
      type: {
        id: 109,
        name: 'Successful Dribbles',
        code: 'successful-dribbles',
        developer_name: 'SUCCESSFUL_DRIBBLES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630135,
      fixture_id: 19104333,
      type_id: 49,
      participant_id: 2394,
      data: {
        value: 4,
      },
      location: 'home',
      type: {
        id: 49,
        name: 'Shots Insidebox',
        code: 'shots-insidebox',
        developer_name: 'SHOTS_INSIDEBOX',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630140,
      fixture_id: 19104333,
      type_id: 108,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 108,
        name: 'Dribble Attempts',
        code: 'dribble-attempts',
        developer_name: 'DRIBBLED_ATTEMPTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630141,
      fixture_id: 19104333,
      type_id: 109,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 109,
        name: 'Successful Dribbles',
        code: 'successful-dribbles',
        developer_name: 'SUCCESSFUL_DRIBBLES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630394,
      fixture_id: 19104333,
      type_id: 117,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 117,
        name: 'Key Passes',
        code: 'key-passes',
        developer_name: 'KEY_PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628697,
      fixture_id: 19104333,
      type_id: 81,
      participant_id: 2394,
      data: {
        value: 137,
      },
      location: 'home',
      type: {
        id: 81,
        name: 'Successful Passes',
        code: 'successful-passes',
        developer_name: 'SUCCESSFUL_PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628209,
      fixture_id: 19104333,
      type_id: 45,
      participant_id: 2394,
      data: {
        value: 51,
      },
      location: 'home',
      type: {
        id: 45,
        name: 'Ball Possession %',
        code: 'ball-possession',
        developer_name: 'BALL_POSSESSION',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629239,
      fixture_id: 19104333,
      type_id: 77,
      participant_id: 2905,
      data: {
        value: 5,
      },
      location: 'away',
      type: {
        id: 77,
        name: 'Challenges',
        code: 'challenges',
        developer_name: 'CHALLENGES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33628714,
      fixture_id: 19104333,
      type_id: 52,
      participant_id: 2394,
      data: {
        value: 2,
      },
      location: 'home',
      type: {
        id: 52,
        name: 'Goals',
        code: 'goals',
        developer_name: 'GOALS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629562,
      fixture_id: 19104333,
      type_id: 56,
      participant_id: 2394,
      data: {
        value: 4,
      },
      location: 'home',
      type: {
        id: 56,
        name: 'Fouls',
        code: 'fouls',
        developer_name: 'FOULS',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33628699,
      fixture_id: 19104333,
      type_id: 80,
      participant_id: 2905,
      data: {
        value: 163,
      },
      location: 'away',
      type: {
        id: 80,
        name: 'Passes',
        code: 'passes',
        developer_name: 'PASSES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33634438,
      fixture_id: 19104333,
      type_id: 79,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 79,
        name: 'Assists',
        code: 'assists',
        developer_name: 'ASSISTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33634439,
      fixture_id: 19104333,
      type_id: 79,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 79,
        name: 'Assists',
        code: 'assists',
        developer_name: 'ASSISTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630139,
      fixture_id: 19104333,
      type_id: 49,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 49,
        name: 'Shots Insidebox',
        code: 'shots-insidebox',
        developer_name: 'SHOTS_INSIDEBOX',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33630143,
      fixture_id: 19104333,
      type_id: 99,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 99,
        name: 'Accurate Crosses',
        code: 'accurate-crosses',
        developer_name: 'ACCURATE_CROSSES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33629294,
      fixture_id: 19104333,
      type_id: 100,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 100,
        name: 'Interceptions',
        code: 'interceptions',
        developer_name: 'INTERCEPTIONS',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33641573,
      fixture_id: 19104333,
      type_id: 87,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 87,
        name: 'Injuries',
        code: 'injuries',
        developer_name: 'INJURIES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33629240,
      fixture_id: 19104333,
      type_id: 65,
      participant_id: 2905,
      data: {
        value: 5,
      },
      location: 'away',
      type: {
        id: 65,
        name: 'Successful Headers',
        code: 'successful-headers',
        developer_name: 'SUCCESSFUL_HEADERS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33641567,
      fixture_id: 19104333,
      type_id: 87,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 87,
        name: 'Injuries',
        code: 'injuries',
        developer_name: 'INJURIES',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33641570,
      fixture_id: 19104333,
      type_id: 54,
      participant_id: 2394,
      data: {
        value: 3,
      },
      location: 'home',
      type: {
        id: 54,
        name: 'Goal Attempts',
        code: 'goal-attempts',
        developer_name: 'GOAL_ATTEMPTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33641568,
      fixture_id: 19104333,
      type_id: 46,
      participant_id: 2394,
      data: {
        value: 21,
      },
      location: 'home',
      type: {
        id: 46,
        name: 'Ball Safe',
        code: 'ball-safe',
        developer_name: 'BALL_SAFE',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33641569,
      fixture_id: 19104333,
      type_id: 85,
      participant_id: 2394,
      data: {
        value: 0,
      },
      location: 'home',
      type: {
        id: 85,
        name: 'Yellowred Cards',
        code: 'yellowred-cards',
        developer_name: 'YELLOWRED_CARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33641572,
      fixture_id: 19104333,
      type_id: 85,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 85,
        name: 'Yellowred Cards',
        code: 'yellowred-cards',
        developer_name: 'YELLOWRED_CARDS',
        model_type: 'statistic',
        stat_group: 'overall',
      },
    },
    {
      id: 33641574,
      fixture_id: 19104333,
      type_id: 54,
      participant_id: 2905,
      data: {
        value: 1,
      },
      location: 'away',
      type: {
        id: 54,
        name: 'Goal Attempts',
        code: 'goal-attempts',
        developer_name: 'GOAL_ATTEMPTS',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33641571,
      fixture_id: 19104333,
      type_id: 46,
      participant_id: 2905,
      data: {
        value: 27,
      },
      location: 'away',
      type: {
        id: 46,
        name: 'Ball Safe',
        code: 'ball-safe',
        developer_name: 'BALL_SAFE',
        model_type: 'statistic',
        stat_group: 'defensive',
      },
    },
    {
      id: 33642679,
      fixture_id: 19104333,
      type_id: 51,
      participant_id: 2394,
      data: {
        value: 1,
      },
      location: 'home',
      type: {
        id: 51,
        name: 'Offsides',
        code: 'offsides',
        developer_name: 'OFFSIDES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
    {
      id: 33642680,
      fixture_id: 19104333,
      type_id: 51,
      participant_id: 2905,
      data: {
        value: 0,
      },
      location: 'away',
      type: {
        id: 51,
        name: 'Offsides',
        code: 'offsides',
        developer_name: 'OFFSIDES',
        model_type: 'statistic',
        stat_group: 'offensive',
      },
    },
  ],
};

const getFixture = async (req, res) => {
  try {
    fixtureId = req.params.id;
    const fixtureData = await requestFixture(fixtureId);
    const leagueStandings = await requestLeagueStandings(fixtureData.league_id);

    const orderedStandings = leagueStandings.sort(
      (a, b) => a.position - b.position
    );
    res.render('fixture', { orderedStandings });
  } catch (err) {
    console.error(err);
    res.status(500).send('Internal Server Error');
  }
};

const fixtureStream = (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  const getFixture = async () => {
    const fixtureDataStream = await requestFixture(fixtureId);
    res.write(`data: ${JSON.stringify(fixtureDataStream)}\n\n`);
  };

  getFixture();

  const intervalId = setInterval(getFixture, 5000);

  req.on('close', () => {
    clearInterval(intervalId);
    res.end();
  });
};

module.exports = {
  getFixture,
  fixtureStream,
};
