const {
  requestLivescores,
  requestTodayFixtures,
} = require('../models/api_fixtures');

testData = [
  {
    id: 18863546,
    sport_id: 1,
    league_id: 82,
    season_id: 21795,
    stage_id: 77464501,
    group_id: null,
    aggregate_id: null,
    round_id: 309301,
    state_id: 1,
    venue_id: 2169,
    name: 'Eintracht Frankfurt vs FC Augsburg',
    starting_at: '2024-04-19 20:30:00',
    result_info: null,
    leg: '1/1',
    details: null,
    length: 90,
    placeholder: false,
    has_odds: true,
    starting_at_timestamp: 1713551400,
    round: {
      id: 309301,
      sport_id: 1,
      league_id: 82,
      season_id: 21795,
      stage_id: 77464501,
      name: '30',
      finished: false,
      is_current: true,
      starting_at: '2024-04-19',
      ending_at: '2024-04-21',
      games_in_current_week: true,
    },
    league: {
      id: 82,
      sport_id: 1,
      country_id: 11,
      name: 'Bundesliga',
      active: true,
      short_code: 'GER BI',
      image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/82.png',
      type: 'league',
      sub_type: 'domestic',
      last_played_at: '2024-04-14 15:30:00',
      category: 1,
      has_jerseys: false,
      country: {
        id: 11,
        continent_id: 1,
        name: 'Germany',
        official_name: 'Federal Republic of Germany',
        fifa_name: 'GER',
        iso2: 'DE',
        iso3: 'DEU',
        latitude: '51.20246505737305',
        longitude: '10.382203102111816',
        borders: [
          'AUT',
          'BEL',
          'CZE',
          'DNK',
          'FRA',
          'LUX',
          'NLD',
          'POL',
          'CHE',
        ],
        image_path:
          'https://cdn.sportmonks.com/images/countries/png/short/de.png',
      },
    },
    scores: [],
    events: [],
    participants: [
      {
        id: 366,
        sport_id: 1,
        country_id: 11,
        venue_id: 2169,
        gender: 'male',
        name: 'Eintracht Frankfurt',
        short_code: 'SGE',
        image_path: 'https://cdn.sportmonks.com/images/soccer/teams/14/366.png',
        founded: 1899,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-13 16:30:00',
        meta: {
          location: 'home',
          winner: null,
          position: 6,
        },
      },
      {
        id: 90,
        sport_id: 1,
        country_id: 11,
        venue_id: 2165,
        gender: 'male',
        name: 'FC Augsburg',
        short_code: 'FCA',
        image_path: 'https://cdn.sportmonks.com/images/soccer/teams/26/90.png',
        founded: 1907,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-12 18:30:00',
        meta: {
          location: 'away',
          winner: null,
          position: 7,
        },
      },
    ],
    periods: [],
    state: {
      id: 1,
      state: 'NS',
      name: 'Not Started',
      short_name: 'NS',
      developer_name: 'NS',
      type: null,
    },
  },
  {
    id: 18903869,
    sport_id: 1,
    league_id: 600,
    season_id: 22057,
    stage_id: 77465302,
    group_id: null,
    aggregate_id: null,
    round_id: 313267,
    state_id: 22,
    venue_id: 340175,
    name: 'Beşiktaş vs Ankaragücü',
    starting_at: '2024-04-19 19:00:00',
    result_info: null,
    leg: '1/1',
    details: null,
    length: 90,
    placeholder: false,
    has_odds: true,
    starting_at_timestamp: 1713546000,
    round: {
      id: 313267,
      sport_id: 1,
      league_id: 600,
      season_id: 22057,
      stage_id: 77465302,
      name: '33',
      finished: false,
      is_current: true,
      starting_at: '2024-04-19',
      ending_at: '2024-04-22',
      games_in_current_week: true,
    },
    league: {
      id: 600,
      sport_id: 1,
      country_id: 404,
      name: 'Super Lig',
      active: true,
      short_code: 'TUR SL',
      image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/24/600.png',
      type: 'league',
      sub_type: 'domestic',
      last_played_at: '2024-04-15 17:00:00',
      category: 2,
      has_jerseys: false,
      country: {
        id: 404,
        continent_id: 2,
        name: 'Turkey',
        official_name: 'Republic of Turkey',
        fifa_name: 'TUR',
        iso2: 'TR',
        iso3: 'TUR',
        latitude: '39.05101013183594',
        longitude: '34.93033981323242',
        borders: ['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IRQ', 'SYR'],
        image_path:
          'https://cdn.sportmonks.com/images/countries/png/short/tr.png',
      },
    },
    scores: [
      {
        id: 14252460,
        fixture_id: 18903869,
        type_id: 1,
        participant_id: 554,
        score: {
          goals: 1,
          participant: 'home',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252461,
        fixture_id: 18903869,
        type_id: 1,
        participant_id: 3470,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252462,
        fixture_id: 18903869,
        type_id: 1525,
        participant_id: 3470,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: 'CURRENT',
      },
      {
        id: 14252463,
        fixture_id: 18903869,
        type_id: 1525,
        participant_id: 554,
        score: {
          goals: 1,
          participant: 'home',
        },
        description: 'CURRENT',
      },
      {
        id: 14252882,
        fixture_id: 18903869,
        type_id: 2,
        participant_id: 554,
        score: {
          goals: 1,
          participant: 'home',
        },
        description: '2ND_HALF',
      },
      {
        id: 14252883,
        fixture_id: 18903869,
        type_id: 2,
        participant_id: 3470,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: '2ND_HALF',
      },
    ],
    events: [
      {
        id: 111505163,
        fixture_id: 18903869,
        period_id: 5360823,
        participant_id: 554,
        type_id: 14,
        section: 'event',
        player_id: 10966299,
        related_player_id: 164132,
        player_name: 'Ernest Muci',
        related_player_name: 'Gedson Fernandes',
        result: '1-0',
        info: null,
        addition: '1st Goal',
        minute: 18,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1522,
      },
      {
        id: 111505721,
        fixture_id: 18903869,
        period_id: 5360823,
        participant_id: 554,
        type_id: 19,
        section: 'event',
        player_id: 26965,
        related_player_id: null,
        player_name: 'Jonas Svensson',
        related_player_name: null,
        result: null,
        info: 'Foul',
        addition: null,
        minute: 31,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1496,
      },
      {
        id: 111506526,
        fixture_id: 18903869,
        period_id: 5360823,
        participant_id: 554,
        type_id: 18,
        section: 'event',
        player_id: 202738,
        related_player_id: 37563154,
        player_name: 'Tayyip Talha Sanuç',
        related_player_name: 'Serkan Emrecan Terzi',
        result: null,
        info: null,
        addition: null,
        minute: 44,
        extra_minute: null,
        injured: true,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1524,
      },
      {
        id: 111508769,
        fixture_id: 18903869,
        period_id: 5360957,
        participant_id: 3470,
        type_id: 18,
        section: 'event',
        player_id: 160165,
        related_player_id: 392162,
        player_name: 'Pedrinho',
        related_player_name: 'Ali Kaan Güneren',
        result: null,
        info: null,
        addition: null,
        minute: 58,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: null,
      },
    ],
    participants: [
      {
        id: 554,
        sport_id: 1,
        country_id: 404,
        venue_id: 340175,
        gender: 'male',
        name: 'Beşiktaş',
        short_code: 'BES',
        image_path: 'https://cdn.sportmonks.com/images/soccer/teams/10/554.png',
        founded: 1903,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-13 16:00:00',
        meta: {
          location: 'home',
          winner: null,
          position: 4,
        },
      },
      {
        id: 3470,
        sport_id: 1,
        country_id: 404,
        venue_id: 2021,
        gender: 'male',
        name: 'Ankaragücü',
        short_code: null,
        image_path:
          'https://cdn.sportmonks.com/images/soccer/teams/14/3470.png',
        founded: 1910,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-13 13:00:00',
        meta: {
          location: 'away',
          winner: null,
          position: 13,
        },
      },
    ],
    periods: [
      {
        id: 5360823,
        fixture_id: 18903869,
        type_id: 1,
        started: 1713546104,
        ended: 1713548995,
        counts_from: 0,
        ticking: false,
        sort_order: 1,
        description: '1st-half',
        time_added: 2,
        period_length: 45,
        minutes: 48,
        seconds: 11,
        has_timer: false,
      },
      {
        id: 5360957,
        fixture_id: 18903869,
        type_id: 2,
        started: 1713550035,
        ended: null,
        counts_from: 45,
        ticking: true,
        sort_order: 2,
        description: '2nd-half',
        time_added: null,
        period_length: 45,
        minutes: 58,
        seconds: 56,
        has_timer: true,
      },
    ],
    state: {
      id: 22,
      state: 'INPLAY_2ND_HALF',
      name: '2nd Half',
      short_name: '2nd',
      developer_name: 'INPLAY_2ND_HALF',
      type: {
        id: 2,
        name: '2nd Half',
        code: '2nd-half',
        developer_name: '2ND_HALF',
        model_type: 'period',
        stat_group: null,
      },
    },
  },
  {
    id: 19104358,
    sport_id: 1,
    league_id: 271,
    season_id: 21644,
    stage_id: 77463995,
    group_id: null,
    aggregate_id: null,
    round_id: 336022,
    state_id: 22,
    venue_id: 318820,
    name: 'Randers vs OB',
    starting_at: '2024-04-19 19:00:00',
    result_info: null,
    leg: '1/1',
    details: null,
    length: 90,
    placeholder: false,
    has_odds: true,
    starting_at_timestamp: 1713546000,
    round: {
      id: 336022,
      sport_id: 1,
      league_id: 271,
      season_id: 21644,
      stage_id: 77463995,
      name: '4',
      finished: false,
      is_current: true,
      starting_at: '2024-04-19',
      ending_at: '2024-04-21',
      games_in_current_week: true,
    },
    league: {
      id: 271,
      sport_id: 1,
      country_id: 320,
      name: 'Superliga',
      active: true,
      short_code: 'DNK SL',
      image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/271.png',
      type: 'league',
      sub_type: 'domestic',
      last_played_at: '2024-04-15 17:00:00',
      category: 2,
      has_jerseys: false,
      country: {
        id: 320,
        continent_id: 1,
        name: 'Denmark',
        official_name: 'Kingdom of Denmark',
        fifa_name: 'DEN',
        iso2: 'DK',
        iso3: 'DNK',
        latitude: '56.10176086425781',
        longitude: '9.555907249450684',
        borders: ['DEU'],
        image_path:
          'https://cdn.sportmonks.com/images/countries/png/short/dk.png',
      },
    },
    scores: [
      {
        id: 14252500,
        fixture_id: 19104358,
        type_id: 1525,
        participant_id: 2356,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: 'CURRENT',
      },
      {
        id: 14252494,
        fixture_id: 19104358,
        type_id: 1,
        participant_id: 2356,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252495,
        fixture_id: 19104358,
        type_id: 1,
        participant_id: 1789,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252501,
        fixture_id: 19104358,
        type_id: 1525,
        participant_id: 1789,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: 'CURRENT',
      },
      {
        id: 14252898,
        fixture_id: 19104358,
        type_id: 2,
        participant_id: 2356,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: '2ND_HALF',
      },
      {
        id: 14252899,
        fixture_id: 19104358,
        type_id: 2,
        participant_id: 1789,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: '2ND_HALF',
      },
    ],
    events: [
      {
        id: 111505889,
        fixture_id: 19104358,
        period_id: 5360832,
        participant_id: 2356,
        type_id: 19,
        section: 'event',
        player_id: 37622817,
        related_player_id: null,
        player_name: 'Mohammed Fuseini',
        related_player_name: null,
        result: null,
        info: null,
        addition: null,
        minute: 32,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1496,
      },
      {
        id: 111505641,
        fixture_id: 19104358,
        period_id: 5360832,
        participant_id: 1789,
        type_id: 19,
        section: 'event',
        player_id: 418253,
        related_player_id: null,
        player_name: 'Sven Köhler',
        related_player_name: null,
        result: null,
        info: 'Foul',
        addition: null,
        minute: 29,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1496,
      },
      {
        id: 111508744,
        fixture_id: 19104358,
        period_id: 5360965,
        participant_id: 1789,
        type_id: 18,
        section: 'event',
        player_id: 37259996,
        related_player_id: 37591584,
        player_name: 'Louicius Don Deedson',
        related_player_name: 'Luca Kjerrumgaard',
        result: null,
        info: null,
        addition: null,
        minute: 58,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: null,
      },
      {
        id: 111508745,
        fixture_id: 19104358,
        period_id: 5360965,
        participant_id: 1789,
        type_id: 18,
        section: 'event',
        player_id: 37627140,
        related_player_id: 25792,
        player_name: 'Charly Nouck',
        related_player_name: 'Leeroy Owusu',
        result: null,
        info: null,
        addition: null,
        minute: 58,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: null,
      },
      {
        id: 111507935,
        fixture_id: 19104358,
        period_id: 5360965,
        participant_id: 1789,
        type_id: 18,
        section: 'event',
        player_id: 84225,
        related_player_id: 37418793,
        player_name: 'Nicklas Mouritsen',
        related_player_name: 'James Gomez',
        result: null,
        info: null,
        addition: null,
        minute: 46,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111508247,
        fixture_id: 19104358,
        period_id: 5360965,
        participant_id: 2356,
        type_id: 19,
        section: 'event',
        player_id: 25577,
        related_player_id: null,
        player_name: 'Wessel Dammers',
        related_player_name: null,
        result: null,
        info: 'Foul',
        addition: null,
        minute: 50,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1496,
      },
    ],
    participants: [
      {
        id: 2356,
        sport_id: 1,
        country_id: 320,
        venue_id: 318820,
        gender: 'male',
        name: 'Randers',
        short_code: 'RDF',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/teams/20/2356.png',
        founded: 2003,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-14 12:00:00',
        meta: {
          location: 'home',
          winner: null,
          position: 1,
        },
      },
      {
        id: 1789,
        sport_id: 1,
        country_id: 320,
        venue_id: 214349,
        gender: 'male',
        name: 'OB',
        short_code: 'ODE',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/teams/29/1789.png',
        founded: 1889,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-12 17:00:00',
        meta: {
          location: 'away',
          winner: null,
          position: 3,
        },
      },
    ],
    periods: [
      {
        id: 5360832,
        fixture_id: 19104358,
        type_id: 1,
        started: 1713546142,
        ended: 1713549014,
        counts_from: 0,
        ticking: false,
        sort_order: 1,
        description: '1st-half',
        time_added: 2,
        period_length: 45,
        minutes: 47,
        seconds: 52,
        has_timer: false,
      },
      {
        id: 5360965,
        fixture_id: 19104358,
        type_id: 2,
        started: 1713550001,
        ended: null,
        counts_from: 45,
        ticking: true,
        sort_order: 2,
        description: '2nd-half',
        time_added: 4,
        period_length: 45,
        minutes: 59,
        seconds: 30,
        has_timer: true,
      },
    ],
    state: {
      id: 22,
      state: 'INPLAY_2ND_HALF',
      name: '2nd Half',
      short_name: '2nd',
      developer_name: 'INPLAY_2ND_HALF',
      type: {
        id: 2,
        name: '2nd Half',
        code: '2nd-half',
        developer_name: '2ND_HALF',
        model_type: 'period',
        stat_group: null,
      },
    },
  },
  {
    id: 18870659,
    sport_id: 1,
    league_id: 384,
    season_id: 21818,
    stage_id: 77464586,
    group_id: null,
    aggregate_id: null,
    round_id: 309932,
    state_id: 22,
    venue_id: 86,
    name: 'Genoa vs Lazio',
    starting_at: '2024-04-19 18:30:00',
    result_info: null,
    leg: '1/1',
    details: null,
    length: 90,
    placeholder: false,
    has_odds: true,
    starting_at_timestamp: 1713544200,
    round: {
      id: 309932,
      sport_id: 1,
      league_id: 384,
      season_id: 21818,
      stage_id: 77464586,
      name: '33',
      finished: false,
      is_current: true,
      starting_at: '2024-04-19',
      ending_at: '2024-04-22',
      games_in_current_week: true,
    },
    league: {
      id: 384,
      sport_id: 1,
      country_id: 251,
      name: 'Serie A',
      active: true,
      short_code: 'ITA SA',
      image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/0/384.png',
      type: 'league',
      sub_type: 'domestic',
      last_played_at: '2024-04-15 18:45:00',
      category: 1,
      has_jerseys: false,
      country: {
        id: 251,
        continent_id: 1,
        name: 'Italy',
        official_name: 'Italian Republic',
        fifa_name: 'ITA',
        iso2: 'IT',
        iso3: 'ITA',
        latitude: '42.7669792175293',
        longitude: '12.493823051452637',
        borders: ['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT'],
        image_path:
          'https://cdn.sportmonks.com/images/countries/png/short/it.png',
      },
    },
    scores: [
      {
        id: 14252220,
        fixture_id: 18870659,
        type_id: 1,
        participant_id: 102,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252221,
        fixture_id: 18870659,
        type_id: 1,
        participant_id: 43,
        score: {
          goals: 0,
          participant: 'away',
        },
        description: '1ST_HALF',
      },
      {
        id: 14252222,
        fixture_id: 18870659,
        type_id: 1525,
        participant_id: 102,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: 'CURRENT',
      },
      {
        id: 14252223,
        fixture_id: 18870659,
        type_id: 1525,
        participant_id: 43,
        score: {
          goals: 1,
          participant: 'away',
        },
        description: 'CURRENT',
      },
      {
        id: 14252630,
        fixture_id: 18870659,
        type_id: 2,
        participant_id: 102,
        score: {
          goals: 0,
          participant: 'home',
        },
        description: '2ND_HALF',
      },
      {
        id: 14252631,
        fixture_id: 18870659,
        type_id: 2,
        participant_id: 43,
        score: {
          goals: 1,
          participant: 'away',
        },
        description: '2ND_HALF',
      },
    ],
    events: [
      {
        id: 111499962,
        fixture_id: 18870659,
        period_id: 5360743,
        participant_id: 43,
        type_id: 19,
        section: 'event',
        player_id: 133391,
        related_player_id: null,
        player_name: 'Nicolò Casale',
        related_player_name: null,
        result: null,
        info: 'Foul',
        addition: null,
        minute: 16,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1496,
      },
      {
        id: 111505797,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 18,
        section: 'event',
        player_id: 129202,
        related_player_id: 133391,
        player_name: 'Alessio Romagnoli',
        related_player_name: 'Nicolò Casale',
        result: null,
        info: null,
        addition: null,
        minute: 46,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111507115,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 14,
        section: 'event',
        player_id: 827,
        related_player_id: 310131,
        player_name: 'Luis Alberto',
        related_player_name: 'Daichi Kamada',
        result: '0-1',
        info: null,
        addition: '1st Goal',
        minute: 67,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1522,
      },
      {
        id: 111507238,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 18,
        section: 'event',
        player_id: 129476,
        related_player_id: 524055,
        player_name: 'Danilo Cataldi',
        related_player_name: 'Taty Castellanos',
        result: null,
        info: null,
        addition: null,
        minute: 68,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111507980,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 102,
        type_id: 18,
        section: 'event',
        player_id: 131637,
        related_player_id: 537823,
        player_name: 'Stefano Sabelli',
        related_player_name: 'Alessandro Vogliacco',
        result: null,
        info: null,
        addition: null,
        minute: 79,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111507224,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 102,
        type_id: 18,
        section: 'event',
        player_id: 31670,
        related_player_id: 23596,
        player_name: 'Milan Badelj ',
        related_player_name: 'Kevin Strootman',
        result: null,
        info: null,
        addition: null,
        minute: 68,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111507245,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 18,
        section: 'event',
        player_id: 1923,
        related_player_id: 129454,
        player_name: 'Pedro',
        related_player_name: 'Felipe Anderson',
        result: null,
        info: null,
        addition: null,
        minute: 68,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111508620,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 102,
        type_id: 18,
        section: 'event',
        player_id: 25120,
        related_player_id: 11705287,
        player_name: 'Morten Thorsby',
        related_player_name: 'Morten Frendrup',
        result: null,
        info: null,
        addition: null,
        minute: 89,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111508523,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 19,
        section: 'event',
        player_id: 129476,
        related_player_id: null,
        player_name: 'Danilo Cataldi',
        related_player_name: null,
        result: null,
        info: 'Argument',
        addition: null,
        minute: 87,
        extra_minute: null,
        injured: null,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1497,
      },
      {
        id: 111508409,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 43,
        type_id: 18,
        section: 'event',
        player_id: 30482209,
        related_player_id: 827,
        player_name: 'Nicolò Rovella ',
        related_player_name: 'Luis Alberto',
        result: null,
        info: null,
        addition: null,
        minute: 86,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
      {
        id: 111508563,
        fixture_id: 18870659,
        period_id: 5360743,
        participant_id: 102,
        type_id: 19,
        section: 'event',
        player_id: 537823,
        related_player_id: null,
        player_name: 'Alessandro Vogliacco',
        related_player_name: null,
        result: null,
        info: 'Argument',
        addition: null,
        minute: 17,
        extra_minute: null,
        injured: null,
        on_bench: true,
        coach_id: null,
        sub_type_id: 1497,
      },
      {
        id: 111504551,
        fixture_id: 18870659,
        period_id: 5360743,
        participant_id: 43,
        type_id: 18,
        section: 'event',
        player_id: 129603,
        related_player_id: 131999,
        player_name: 'Elseid Hysaj',
        related_player_name: 'Manuel Lazzari',
        result: null,
        info: null,
        addition: null,
        minute: 36,
        extra_minute: null,
        injured: true,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1524,
      },
      {
        id: 111507220,
        fixture_id: 18870659,
        period_id: 5360871,
        participant_id: 102,
        type_id: 18,
        section: 'event',
        player_id: 37565662,
        related_player_id: 133599,
        player_name: 'David Ankeye',
        related_player_name: 'Caleb Ekuban',
        result: null,
        info: null,
        addition: null,
        minute: 68,
        extra_minute: null,
        injured: false,
        on_bench: false,
        coach_id: null,
        sub_type_id: 1523,
      },
    ],
    participants: [
      {
        id: 102,
        sport_id: 1,
        country_id: 251,
        venue_id: 86,
        gender: 'male',
        name: 'Genoa',
        short_code: 'GEN',
        image_path: 'https://cdn.sportmonks.com/images/soccer/teams/6/102.png',
        founded: 1893,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-15 16:30:00',
        meta: {
          location: 'home',
          winner: null,
          position: 12,
        },
      },
      {
        id: 43,
        sport_id: 1,
        country_id: 251,
        venue_id: 7189,
        gender: 'male',
        name: 'Lazio',
        short_code: 'LAZ',
        image_path: 'https://cdn.sportmonks.com/images/soccer/teams/11/43.png',
        founded: 1900,
        type: 'domestic',
        placeholder: false,
        last_played_at: '2024-04-12 18:45:00',
        meta: {
          location: 'away',
          winner: null,
          position: 8,
        },
      },
    ],
    periods: [
      {
        id: 5360743,
        fixture_id: 18870659,
        type_id: 1,
        started: 1713544298,
        ended: 1713547148,
        counts_from: 0,
        ticking: false,
        sort_order: 1,
        description: '1st-half',
        time_added: 1,
        period_length: 45,
        minutes: 47,
        seconds: 30,
        has_timer: false,
      },
      {
        id: 5360871,
        fixture_id: 18870659,
        type_id: 2,
        started: 1713548024,
        ended: null,
        counts_from: 45,
        ticking: true,
        sort_order: 2,
        description: '2nd-half',
        time_added: 4,
        period_length: 45,
        minutes: 92,
        seconds: 27,
        has_timer: true,
      },
    ],
    state: {
      id: 22,
      state: 'INPLAY_2ND_HALF',
      name: '2nd Half',
      short_name: '2nd',
      developer_name: 'INPLAY_2ND_HALF',
      type: {
        id: 2,
        name: '2nd Half',
        code: '2nd-half',
        developer_name: '2ND_HALF',
        model_type: 'period',
        stat_group: null,
      },
    },
  },
];

const getIndex = async (req, res) => {
  try {
    res.render('index');
  } catch (err) {
    console.error(err);
    res.status(500).send('Internal Server Error');
  }
};

const livescoreStream = (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  const getLivescore = async () => {
    // const livescoresData = testData;
    const livescoresData = await requestLivescores();
    const fixturesToday = await requestTodayFixtures();

    if (livescoresData) {
      const orderedData = livescoresData.sort(
        (a, b) => b.starting_at_timestamp - a.starting_at_timestamp
      );

      res.write(`data: ${JSON.stringify(orderedData)}\n\n`);
    } else {
      const orderedData = fixturesToday.sort(
        (a, b) => b.starting_at_timestamp - a.starting_at_timestamp
      );
      res.write(`data: ${JSON.stringify(orderedData)}\n\n`);
    }
  };

  getLivescore();

  const intervalId = setInterval(getLivescore, 30000);

  req.on('close', () => {
    clearInterval(intervalId);
    res.end();
  });
};

module.exports = {
  getIndex,
  livescoreStream,
};
